### ISSUE TITLE
Switch to newer engine

### ISSUE THREAD

**Issue by pizzadude** [flathub/info.urbanterror.UrbanTerror#1]
Can you switch the flatpak to https://github.com/mickael9/ioq3.git because it contains fixes for alt-tabbing and uses SDL2?

**Comment by Mailaender** [comment]
No, the point of Flathub is to ship the game like the developers intended and they have their own custom ioq3 fork.

**Comment by pizzadude** [comment]
@Mailaender The official installer from the official site includes this engine as an option. And you can barely play the game in wayland with the "default" engine because the mouse keeps jumping all over the place.

**Comment by Mailaender** [comment]
That personal repository does not even have tags. Have you tried to submit the changes upstream?

**Comment by pizzadude** [comment]
I'm not the developer.

If you download "UrbanTerror43_ded.tar.gz" from Urban Terror's website and run the install script it gives you the option to use that engine linked above.

If you look at the repo for Urban Terror's "default" engine, you will notice the same dev has contributed.

**Comment by Mailaender** [comment]
Urge upstream to make a new maintenance release then.

**Comment by pizzadude** [comment]
🤦

**Comment by Mailaender** [comment]
Instead of being rude you are free to submit a manifest for the engine fork like https://github.com/flathub/io.github.ec_.Quake3e.OpenArena did.
